#!/bin/bash

# Script per applicare la configurazione Supabase locale
# Da eseguire dalla directory principale del progetto

set -e

echo "🔧 Applicazione configurazione Supabase locale..."

# La directory corrente dovrebbe essere la root del progetto
PROJECT_DIR="$(pwd)"
echo "📁 Directory corrente: $PROJECT_DIR"

# Verifica struttura progetto
if [ ! -d "supabase" ] || [ ! -d "src" ]; then
    echo "❌ Errore: Esegui questo script dalla directory principale del progetto!"
    echo "   Devono esistere le cartelle 'supabase' e 'src'"
    exit 1
fi

# File da modificare
CLIENT_FILE="src/integrations/supabase/client.ts"
if [ ! -f "$CLIENT_FILE" ]; then
    echo "❌ Errore: File $CLIENT_FILE non trovato!"
    exit 1
fi

# Backup
echo "💾 Backup del file originale..."
cp "$CLIENT_FILE" "${CLIENT_FILE}.backup.$(date +%Y%m%d_%H%M%S)"

# Modifica
echo "✏️  Modifica del file client.ts..."
cat > "$CLIENT_FILE" << 'EOF'
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use local Supabase instance - detect if accessing via localhost or remote IP
const getSupabaseUrl = () => {
  const hostname = window.location.hostname;
  // If accessing via localhost, use localhost
  if (hostname === 'localhost' || hostname === '127.0.0.1') {
    return "http://localhost:8000";
  }
  // If accessing via remote IP or .local domain, use that IP/hostname
  return `http://${hostname}:8000`;
};

const SUPABASE_URL = getSupabaseUrl();
// Default Supabase local ANON key
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
EOF

echo "✅ File modificato!"

# Riavvia Docker
echo "🐳 Riavvio Docker..."
cd scripts/docker

docker compose down
docker compose build --no-cache
docker compose up -d

echo "⏳ Attesa avvio (30 secondi)..."
sleep 30

echo ""
echo "✅ CONFIGURAZIONE COMPLETATA!"
echo ""
echo "🌐 App HACCP:"
echo "   http://192.168.0.53"
echo ""
echo "🗄️  Supabase Studio:"
echo "   http://192.168.0.53:54323"
echo "   (lascia le credenziali vuote)"
echo ""
