#!/bin/bash

# Script per applicare la configurazione locale Supabase
# Modifica automaticamente il file client.ts e riavvia Docker

set -e  # Esci in caso di errore

echo "🔧 Applicazione configurazione Supabase locale..."

# Trova la directory del progetto
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
echo "📁 Directory progetto: $PROJECT_DIR"

# Verifica che il file esista
CLIENT_FILE="$PROJECT_DIR/src/integrations/supabase/client.ts"
if [ ! -f "$CLIENT_FILE" ]; then
    echo "❌ Errore: File $CLIENT_FILE non trovato!"
    exit 1
fi

# Backup del file originale
echo "💾 Backup del file originale..."
cp "$CLIENT_FILE" "$CLIENT_FILE.backup"

# Crea il nuovo contenuto
echo "✏️  Modifica del file client.ts..."
cat > "$CLIENT_FILE" << 'EOF'
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use local Supabase instance - detect if accessing via localhost or remote IP
const getSupabaseUrl = () => {
  const hostname = window.location.hostname;
  // If accessing via localhost, use localhost
  if (hostname === 'localhost' || hostname === '127.0.0.1') {
    return "http://localhost:8000";
  }
  // If accessing via remote IP or .local domain, use that IP/hostname
  return `http://${hostname}:8000`;
};

const SUPABASE_URL = getSupabaseUrl();
// Default Supabase local ANON key
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
EOF

echo "✅ File client.ts modificato con successo!"

# Riavvia Docker
echo "🐳 Riavvio Docker containers..."
cd "$PROJECT_DIR/scripts/docker"

if [ -f "docker-compose.yml" ]; then
    echo "⏹️  Arresto containers esistenti..."
    docker compose down
    
    echo "🏗️  Rebuild dell'immagine..."
    docker compose build --no-cache
    
    echo "🚀 Avvio containers..."
    docker compose up -d
    
    echo "⏳ Attesa avvio servizi (30 secondi)..."
    sleep 30
    
    echo ""
    echo "✅ Configurazione completata!"
    echo ""
    echo "🌐 L'app HACCP è accessibile su:"
    echo "   - http://localhost (da Raspberry Pi)"
    echo "   - http://192.168.0.53 (dalla tua rete)"
    echo "   - http://haccp-app.local (se configurato mDNS)"
    echo ""
    echo "🗄️  Supabase Studio è accessibile su:"
    echo "   - http://192.168.0.53:54323"
    echo "   - Credenziali: lascia vuoti entrambi i campi"
    echo ""
    echo "🔍 Per vedere i logs dei containers:"
    echo "   docker compose logs -f"
    echo ""
else
    echo "❌ Errore: docker-compose.yml non trovato!"
    echo "Ripristino backup..."
    cp "$CLIENT_FILE.backup" "$CLIENT_FILE"
    exit 1
fi
