#!/bin/bash

# Script semplificato per setup app HACCP con Supabase locale già attivo

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() { echo -e "${GREEN}[✓]${NC} $1"; }
print_error() { echo -e "${RED}[✗]${NC} $1"; }
print_info() { echo -e "${BLUE}[ℹ]${NC} $1"; }

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║     HACCP APP - Setup con Supabase Locale                     ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Configurazione
GITHUB_REPO="git@github.com:igorrodi/haccp-tracciabilita.git"
GITHUB_BRANCH="main"
APP_DIR="$HOME/haccp-app"
SUPABASE_URL="http://localhost:8000"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"

# ============================================================================
# FASE 1: Clone Repository
# ============================================================================

echo ""
print_info "FASE 1: Download codice da GitHub..."

if [ -d "$APP_DIR" ]; then
    print_info "Directory esistente trovata. Aggiorno..."
    cd "$APP_DIR"
    git fetch origin
    git reset --hard origin/$GITHUB_BRANCH
else
    print_info "Clono repository..."
    git clone -b "$GITHUB_BRANCH" "$GITHUB_REPO" "$APP_DIR"
    cd "$APP_DIR"
fi

print_status "Codice scaricato!"

# ============================================================================
# FASE 2: Applica Migrazioni Database
# ============================================================================

echo ""
print_info "FASE 2: Creazione tabelle nel database locale..."

# Verifica che PostgreSQL client sia installato
if ! command -v psql &> /dev/null; then
    print_info "Installazione PostgreSQL client..."
    sudo apt-get update
    sudo apt-get install -y postgresql-client
fi

# Applica tutte le migrazioni
print_info "Applico migrazioni database..."
cd "$APP_DIR"

# Applica migrazioni
if [ -d "supabase/migrations" ]; then
    for migration in supabase/migrations/*.sql; do
        if [ -f "$migration" ]; then
            print_info "Applico: $(basename $migration)"
            PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -f "$migration" 2>&1 | grep -v "NOTICE:" || {
                print_error "Errore in $(basename $migration)"
                print_info "Continuo con le altre migrazioni..."
            }
        fi
    done
    print_status "Migrazioni applicate!"
else
    print_error "Cartella migrazioni non trovata!"
fi

# ============================================================================
# FASE 3: Configura Client Supabase per uso locale
# ============================================================================

echo ""
print_info "FASE 3: Configurazione client Supabase..."

cat > "$APP_DIR/src/integrations/supabase/client.ts" << 'EOF'
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use local Supabase instance - detect if accessing via localhost or remote IP
const getSupabaseUrl = () => {
  const hostname = window.location.hostname;
  // If accessing via localhost, use localhost
  if (hostname === 'localhost' || hostname === '127.0.0.1') {
    return "http://localhost:8000";
  }
  // If accessing via remote IP or .local domain, use that IP/hostname
  return `http://${hostname}:8000`;
};

const SUPABASE_URL = getSupabaseUrl();
// Default Supabase local ANON key
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
EOF

print_status "Client configurato per Supabase locale!"

# ============================================================================
# FASE 4: Installa Dipendenze e Build App
# ============================================================================

echo ""
print_info "FASE 4: Build applicazione..."

cd "$APP_DIR"

# Installa Node.js se necessario
if ! command -v node &> /dev/null; then
    print_info "Installazione Node.js..."
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    sudo apt-get install -y nodejs
fi

# Installa dipendenze
print_info "Installazione dipendenze npm..."
npm install

# Build
print_info "Build in corso..."
npm run build

print_status "Build completata!"

# ============================================================================
# FASE 5: Setup Docker per l'app
# ============================================================================

echo ""
print_info "FASE 5: Configurazione Docker..."

# Crea Dockerfile se non esiste
cat > "$APP_DIR/Dockerfile" << 'EOF'
FROM nginx:alpine

# Copia i file buildati
COPY dist /usr/share/nginx/html

# Copia configurazione nginx personalizzata
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
EOF

# Crea nginx.conf per l'app
cat > "$APP_DIR/nginx.conf" << 'EOF'
server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Gestione SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache per asset statici
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
EOF

# Build immagine Docker
print_info "Build immagine Docker..."
cd "$APP_DIR"
docker build -t haccp-app:latest .

# Ferma container esistente se presente
docker stop haccp-app 2>/dev/null || true
docker rm haccp-app 2>/dev/null || true

# Avvia nuovo container
print_info "Avvio container..."
docker run -d \
  --name haccp-app \
  --restart unless-stopped \
  -p 3000:80 \
  haccp-app:latest

print_status "Container avviato sulla porta 3000!"

# ============================================================================
# FASE 6: Configura Nginx come Reverse Proxy
# ============================================================================

echo ""
print_info "FASE 6: Configurazione Nginx reverse proxy..."

sudo tee /etc/nginx/sites-available/haccp-app > /dev/null << 'EOF'
server {
    listen 80;
    server_name haccp-app.local;

    # Redirect HTTP to HTTPS
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name haccp-app.local;

    ssl_certificate /etc/ssl/certs/haccp-app.crt;
    ssl_certificate_key /etc/ssl/private/haccp-app.key;

    # Proxy per l'app
    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy per Supabase API
    location /supabase/ {
        proxy_pass http://localhost:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
EOF

# Genera certificati SSL self-signed
if [ ! -f /etc/ssl/certs/haccp-app.crt ]; then
    print_info "Generazione certificati SSL..."
    sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout /etc/ssl/private/haccp-app.key \
        -out /etc/ssl/certs/haccp-app.crt \
        -subj "/CN=haccp-app.local"
fi

# Abilita sito
sudo ln -sf /etc/nginx/sites-available/haccp-app /etc/nginx/sites-enabled/
sudo nginx -t && sudo systemctl reload nginx

print_status "Nginx configurato!"

# ============================================================================
# COMPLETAMENTO
# ============================================================================

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                 INSTALLAZIONE COMPLETATA!                     ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
print_status "HACCP App installata e configurata!"
echo ""
print_info "Accedi all'app:"
echo "  • https://haccp-app.local"
echo "  • http://$(hostname -I | awk '{print $1}')"
echo ""
print_info "Supabase Studio:"
echo "  • http://localhost:54323"
echo ""
print_info "Per verificare i log:"
echo "  docker logs -f haccp-app"
echo ""
