// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use local Supabase instance - detect if accessing via localhost or remote IP
const getSupabaseUrl = () => {
  const hostname = window.location.hostname;
  const protocol = window.location.protocol;
  
  // If accessing via localhost, use localhost with HTTP
  if (hostname === 'localhost' || hostname === '127.0.0.1') {
    return "http://localhost:8000";
  }
  
  // If accessing via HTTPS (reverse proxy), use /supabase proxy path
  if (protocol === 'https:') {
    return `${protocol}//${hostname}/supabase`;
  }
  
  // Otherwise use hostname with port 8000
  return `http://${hostname}:8000`;
};

const SUPABASE_URL = getSupabaseUrl();
// Default Supabase local ANON key
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});