// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://domzjvvfcalyzphrizfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvbXpqdnZmY2FseXpwaHJpemZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5Nzg3NTMsImV4cCI6MjA3NDU1NDc1M30.AskCy1bsD3lvA82xV-DEAqSwPJlUWeyzpWAROHGZiBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});